- .gitignore
Reverts irisnet/sdk-js#1
Premature merge
> Revert "WIP: init project"

- README.md
- docs/README.md
- docs/api.md
- package.json
- src/index.js
- src/modules/bank/index.js
- src/modules/distr/index.js
- src/modules/gov/index.js
- src/modules/index.js
- src/modules/module.js
- src/modules/router-cosmos.js
- src/modules/router-iris.js
- src/modules/router.js
- src/modules/slashing/index.js
- src/modules/stake/index.js
- src/modules/tm/index.js
- src/modules/version/index.js
- src/net/http-provider.js
- src/net/index.js
- src/net/ws-provider.js
- src/utils/index.js
- test/test-cosmos.js
- test/test.js
> R4R: Support query some information from LCD

- src/client.ts
- src/modules/index.ts
- src/modules/slashing.ts
- src/types/index.ts
- src/types/slashing.ts
> R4R: Add slashing module

- src/client.ts
- src/modules/bank.ts
- src/modules/distribution.ts
- src/types/distribution.ts
- src/types/gov.ts
- src/types/index.ts
- src/types/params.ts
> Add distribution module

- .gitignore
- Dockerfile
- package.json
- tsconfig.json
- yarn.lock
> R4R: Add typedoc support

- package.json
- src/client.ts
- src/import.d.ts
- src/nets/event-listener.ts
- yarn.lock
> Add EventListener Framework

- src/client.ts
- src/modules/tx.ts
- src/nets/event-listener.ts
- src/types/events.ts
- src/types/index.ts
- src/types/types.ts
> R4R: Add subscribeNewBlock function

- src/nets/event-listener.ts
- src/types/events.ts
> R4R: Add subscribeNewBlockHeader

- src/nets/event-listener.ts
- src/types/events.ts
> R4R: Add subscribeValidatorSetUpdates

- src/modules/bank.ts
- src/nets/event-listener.ts
- src/types/bank.ts
- src/types/events.ts
- src/types/types.ts
- src/utils/crypto.ts
> Add `send` txs listener

- src/modules/staking.ts
- src/nets/event-listener.ts
- src/types/staking.ts
> R4R: Subscribe ValidatorInfoUpdates

- package.json
- src/modules/auth.ts
- src/modules/gov.ts
- src/modules/staking.ts
- src/modules/tx.ts
- src/nets/event-listener.ts
- src/nets/rpc-client.ts
- src/types/events.ts
- src/types/staking.ts
- src/utils/address.ts
- src/utils/crypto.ts
- src/utils/store-keys.ts
- src/utils/utils.ts
- test/bank.test.ts
- test/crypto.test.ts
- test/my.test.ts
- yarn.lock
> R4R: Subscribe Validator Status Updates

- src/client.ts
- src/modules/index.ts
- src/modules/oracle.ts
- src/types/index.ts
- src/types/oracle.ts
- test/staking.test.ts
> R4R: Add oracle queries

- src/modules/index.ts
- src/modules/random.ts
- src/types/index.ts
- src/types/random.ts
> R4R: Add random module

- src/errors.ts
- src/modules/bank.ts
- src/modules/keys.ts
- src/modules/random.ts
- src/modules/service.ts
- src/modules/slashing.ts
- src/modules/staking.ts
- src/modules/tx.ts
- src/nets/event-listener.ts
- src/nets/rpc-client.ts
- src/utils/crypto.ts
- src/utils/utils.ts
> R4R: Add error code mapping

- src/client.ts
- src/import.d.ts
- src/index.ts
- src/modules/keys.ts
- src/modules/tx.ts
- src/types/keystore.ts
- test/basetest.ts
- test/keys.test.ts
> R4R: Keys refactor

- package.json
- src/modules/bank.ts
- src/modules/random.ts
- src/modules/staking.ts
- src/modules/tx.ts
- src/nets/event-listener.ts
- src/nets/rpc-client.ts
- src/nets/ws-client.ts
- src/types/events.ts
- src/types/random.ts
- test/jest.setup.js
- test/my.test.ts
- yarn.lock
> R4R: Refactor event listener

- src/client.ts
- src/modules/asset.ts
- src/modules/index.ts
- src/types/asset.ts
- src/types/index.ts
- test/asset.test.ts
> R4R: Add asset queriers

- src/client.ts
- src/import.d.ts
- src/modules/bank.ts
- src/modules/index.ts
- src/modules/staking.ts
- src/modules/tendermint.ts
- src/modules/tx.ts
- src/nets/event-listener.ts
- src/nets/rpc-client.ts
- src/types/block-result.ts
- src/types/block.ts
- src/types/constants.ts
- src/types/events.ts
- src/types/index.ts
- src/types/query-builder.ts
- src/types/tx.ts
- src/types/validator.ts
- src/utils/utils.ts
- test/tendermint.test.ts
> R4R: Add Tendermint Queriers

- src/client.ts
- src/modules/asset.ts
- src/modules/auth.ts
- src/modules/bank.ts
- src/modules/distribution.ts
- src/modules/gov.ts
- src/modules/keys.ts
- src/modules/oracle.ts
- src/modules/random.ts
- src/modules/service.ts
- src/modules/slashing.ts
- src/modules/staking.ts
- src/modules/tendermint.ts
- src/modules/tx.ts
- src/modules/utils.ts
- src/nets/event-listener.ts
- src/nets/rpc-client.ts
- src/nets/ws-client.ts
- src/types/abci-query.ts
- src/types/events.ts
- src/types/query-builder.ts
- src/types/slashing.ts
- src/utils/address.ts
- src/utils/store-keys.ts
- src/utils/utils.ts
- test/asset.test.ts
- test/my.test.ts
- test/slashing.test.ts
> R4R: Code cleanup

- dist/package.json
- dist/src/modules/token.d.ts
- dist/src/types/token.d.ts
- dist/src/types/token.js
- package.json
- proto/irismod/token/v1/tx.proto
- src/modules/token.ts
- src/types/token.ts
- test/token.test.ts
> #Fixed Mint Token Tx
